application: hwcheck-1224
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: application.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"

skip_files:
- ^(\.git/.*)$
- ^(venv/lib/python2.7/site-packages/MySQL.*)
- ^(\.idea/.*)$
- deploy
- ^(.*/)?.*\.DS_Store$
- ^(.*/)?.*\.py[co]$