"""empty message

Revision ID: 0dfa7bae2299
Revises: d22f6efe905d
Create Date: 2016-01-24 15:47:33.358301

"""

# revision identifiers, used by Alembic.
revision = '0dfa7bae2299'
down_revision = 'd22f6efe905d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem')
    ### end Alembic commands ###
