"""empty message

Revision ID: 5cd9c0b4ec5d
Revises: fb22e8b295a8
Create Date: 2016-01-25 20:54:39.756008

"""

# revision identifiers, used by Alembic.
revision = '5cd9c0b4ec5d'
down_revision = 'fb22e8b295a8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_column('user', 'company')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company', mysql.VARCHAR(collation=u'utf8_bin', length=30), nullable=True))
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'group')
    ### end Alembic commands ###
