"""empty message

Revision ID: 8d1eeedab354
Revises: c08c401b8fd9
Create Date: 2016-02-12 23:01:35.785447

"""

# revision identifiers, used by Alembic.
revision = '8d1eeedab354'
down_revision = 'c08c401b8fd9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_homework_relation',
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('homework_id', sa.Integer(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_homework_relation')
    ### end Alembic commands ###
