"""empty message

Revision ID: c08c401b8fd9
Revises: b1bfd006dc44
Create Date: 2016-02-10 23:57:34.923466

"""

# revision identifiers, used by Alembic.
revision = 'c08c401b8fd9'
down_revision = 'b1bfd006dc44'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework',
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'problem', sa.Column('homework_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'problem_ibfk_1', 'problem', type_='foreignkey')
    op.create_foreign_key(None, 'problem', 'homework', ['homework_id'], ['id'])
    op.drop_column(u'problem', 'date')
    op.drop_column(u'problem', 'group_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'problem', sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'problem', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.create_foreign_key(u'problem_ibfk_1', 'problem', 'group', ['group_id'], ['id'])
    op.drop_column(u'problem', 'homework_id')
    op.drop_table('homework')
    ### end Alembic commands ###
