"""empty message

Revision ID: cfd347279533
Revises: 5cd9c0b4ec5d
Create Date: 2016-01-26 22:22:26.641157

"""

# revision identifiers, used by Alembic.
revision = 'cfd347279533'
down_revision = '5cd9c0b4ec5d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=30), nullable=False))
    op.drop_column('user', 'group')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group', mysql.VARCHAR(collation=u'utf8_bin', length=30), nullable=True))
    op.drop_column('user', 'name')
    ### end Alembic commands ###
