"""empty message

Revision ID: fb22e8b295a8
Revises: 0dfa7bae2299
Create Date: 2016-01-24 17:15:09.971713

"""

# revision identifiers, used by Alembic.
revision = 'fb22e8b295a8'
down_revision = '0dfa7bae2299'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'problem', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'problem_ibfk_1', 'problem', type_='foreignkey')
    op.create_foreign_key(None, 'problem', 'group', ['group_id'], ['id'])
    op.drop_column(u'problem', 'course_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'problem', sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.create_foreign_key(u'problem_ibfk_1', 'problem', 'course', ['course_id'], ['id'])
    op.drop_column(u'problem', 'group_id')
    op.drop_table('group')
    ### end Alembic commands ###
